const std = @import("std");

pub const UDSService = enum(u8) {
    DIAGNOSTIC_SESSION_CONTROL = 0x10,
    ECU_RESET = 0x11,
    CLEAR_DTC = 0x14,
    READ_DTC_INFO = 0x19,
    READ_DATA_BY_ID = 0x22,
    READ_MEMORY_BY_ADDRESS = 0x23,
    SECURITY_ACCESS = 0x27,
    COMMUNICATION_CONTROL = 0x28,
    WRITE_DATA_BY_ID = 0x2E,
    IO_CONTROL = 0x2F,
    ROUTINE_CONTROL = 0x31,
    REQUEST_DOWNLOAD = 0x34,
    TRANSFER_DATA = 0x36,
    REQUEST_TRANSFER_EXIT = 0x37,
    TESTER_PRESENT = 0x3E,
    _,
};

pub const UDSSession = enum(u8) {
    DEFAULT = 0x01,
    PROGRAMMING = 0x02,
    EXTENDED = 0x03,
    FORD_DIAG = 0x85,
    _,
};

pub const DTCSubFunction = enum(u8) {
    REPORT_NUMBER_BY_STATUS = 0x01,
    REPORT_BY_STATUS = 0x02,
    REPORT_SNAPSHOT_ID = 0x03,
    REPORT_SNAPSHOT_BY_DTC = 0x04,
    REPORT_STORED_DATA = 0x06,
    REPORT_PENDING = 0x07,
    REPORT_CONFIRMED = 0x0A,
    REPORT_SUPPORTED_DTC = 0x0F,
    _,
};

pub const NRC = enum(u8) {
    GENERAL_REJECT = 0x10,
    SERVICE_NOT_SUPPORTED = 0x11,
    SUBFUNCTION_NOT_SUPPORTED = 0x12,
    INCORRECT_LENGTH = 0x13,
    RESPONSE_TOO_LONG = 0x14,
    BUSY_REPEAT = 0x21,
    CONDITIONS_NOT_CORRECT = 0x22,
    REQUEST_SEQUENCE_ERROR = 0x24,
    REQUEST_OUT_OF_RANGE = 0x31,
    SECURITY_ACCESS_DENIED = 0x33,
    INVALID_KEY = 0x35,
    EXCEEDED_ATTEMPTS = 0x36,
    TIME_DELAY_NOT_EXPIRED = 0x37,
    UPLOAD_DOWNLOAD_NOT_ACCEPTED = 0x70,
    TRANSFER_SUSPENDED = 0x71,
    GENERAL_PROGRAMMING_FAILURE = 0x72,
    RESPONSE_PENDING = 0x78,
    SUBFUNCTION_NOT_SUPPORTED_IN_SESSION = 0x7E,
    SERVICE_NOT_SUPPORTED_IN_SESSION = 0x7F,
    _,
};
